# docker-compose.yml

version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    priveleged: true

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"

# below docker compose was used on ec2, by transfering the built images directly to ec2
# wasnt able to build there for some issue
# priveleged: true was required on ec2 for unkonwn reason other wise pthread_create() sys call was failing

# version: '3'
# services:
#   server:
#     image: hr-ai-server
#     privileged: true
#     ports:
#       - "82:8080"

#   client:
#     image: hr-ai-client
#     ports:
#       - "81:80"
